.TH RUSTTALE 1 "December 2025" "v0.1.0" "Games"
.SH NAME
rusttale \- A 2D game written in Rust
.SH SYNOPSIS
.B rusttale
.SH DESCRIPTION
\fBrusttale\fR is a 2D game developed using the Tetra engine in Rust.
.SH INSTALLATION
To compile and run the project:
.PP
.B cargo run --release
.SH DEPENDENCIES
See the README file in the main directory for required system libraries (e.g., SDL3).
.SH REPOSITORIES
The source code is available in the following repositories:
.TP
.B rusttale
Main game source code.
.TP
.B resourcetale
Game assets and resources.
.SH AUTHOR
lazypwny751
