.TH RUSTTALE 1 "Décembre 2025" "v0.1.0" "Jeux"
.SH NOM
rusttale \- Un jeu 2D écrit en Rust
.SH SYNOPSIS
.B rusttale
.SH DESCRIPTION
\fBrusttale\fR est un jeu 2D développé avec le moteur Tetra en Rust.
.SH INSTALLATION
Pour compiler et exécuter le projet :
.PP
.B cargo run --release
.SH DÉPENDANCES
Voir le fichier README dans le répertoire principal pour les bibliothèques système requises (par exemple, SDL3).
.SH DÉPÔTS
Le code source est disponible dans les dépôts suivants :
.TP
.B rusttale
Code source principal du jeu.
.TP
.B resourcetale
Ressources et actifs du jeu.
.SH AUTEUR
lazypwny751
